import TextSettings from "../interfaces/TextSettings";

const textSettings: TextSettings = {
  // fontFamily: "Times New Roman",
  // fontFamily: "Arial",
  // fontFamily: "Courier New",
  // fontFamily: "Georgia",
  fontFamily: "Helvetica",
  // fontFamily: "Verdana",
  // fontFamily: "Roboto",
  // fontFamily: "Open Sans",
  fontSize: "16px",
  // fontSize: "14px",
  // fontSize: "18px",
  // fontSize: "20px",
  // fontSize: "24px",
  fontWeight: "normal",
  // fontWeight: "bold",
  // fontWeight: "lighter",
  // fontWeight: "600",
  fontStyle: "normal",
  // fontStyle: "italic",
  // fontStyle: "oblique",
  textOpacity: 1,
  // textOpacity: 0.8,
  // textOpacity: 0.9,
  // textOpacity: 0.7,
  lineHeight: 1.5,
  // lineHeight: 1.2,
  // lineHeight: 1.8,
  // lineHeight: 2,
  color: "black",
  // color: "#333333",
  // color: "#666666",
  // color: "darkgray",
  // color: "navy",
  backgroundColor: "white",
  // backgroundColor: "#f5f5f5",
  // backgroundColor: "#ffffff",
  // backgroundColor: "ivory",
  // backgroundColor: "transparent",
  letterSpacing: 0,
  // letterSpacing: 0.5,
  // letterSpacing: 1,
  // letterSpacing: -0.5,
  wordSpacing: 0,
  // wordSpacing: 2,
  // wordSpacing: 4,
  // wordSpacing: -1,
  // textAlign: "right",
  // textAlign: "left",
  textAlign: "center",
  // textAlign: "justify",
};

// Hard-to-read settings combination:
const hardToReadSettings: TextSettings = {
  fontFamily: "Comic Sans MS",
  fontSize: "12px",
  fontWeight: "normal",
  fontStyle: "normal",
  textOpacity: 0.6,
  lineHeight: 2,
  color: "#999999",
  backgroundColor: "#ffffff",
  letterSpacing: 2,
  wordSpacing: 4,
  textAlign: "justify",
};

export { textSettings, hardToReadSettings };
